name: calendar_plugin
description: A new Flutter plugin project.
version: 1.0.0+0
homepage:

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: CalendarPlugin
      macos:
        pluginClass: CalendarPlugin
